[project]
name = "uv-version"
version = "0.1.0"
description = "Python environment with uv"
readme = "README.md"
authors = [
    { name = "sofiafeiranz", email = "sofiakarmaze@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "pandas<3",
]

[project.scripts]
uv-version = "uv_version:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
